name: app_ebara
description: "Ebara APP"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  geolocator: ^14.0.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  flutter_widget_from_html: ^0.17.1
  html_unescape: ^2.0.0

  path_provider: ^2.1.2
  permission_handler: ^12.0.1
  open_filex: ^4.4.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.14.4
  url_launcher: ^6.3.2
  scrollable_positioned_list: ^0.3.8
  animated_text_kit: ^4.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  provider: ^6.1.5+1
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.14.0
  flutter_map: ^8.2.2
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^7.2.0
  share_plus: ^12.0.1
  connectivity_plus: ^7.0.0
  firebase_analytics: ^12.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  json_serializable: ^6.11.3
  build_runner: ^2.10.4
  animated_theme_switcher: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/logo_fundo.png
  adaptive_icon_background: "#004F9F"
  adaptive_icon_foreground: assets/images/logo_fundo.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
          
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
          
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
          
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic